name: snakemake_pps
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.10.4
  - pip=23.2.1
  - snakemake=7.32.2
  - r-optparse=1.7.3
  - bioconductor-qvalue=2.30.0
  - r-dplyr=1.1.2
  - r-tidyr=1.3.0
  - r-ggplot2=3.4.4
  - r-ggrepel=0.9.4
  - pip:
    - pandas==2.1.1
    - scikit-learn==1.3.0
    - plotnine==0.12.2
    - matplotlib==3.7.2
    - pysam==0.21.0
    - pyplink==1.3.6
    - seaborn==0.12.2
